import { Resend } from 'resend';

export async function sendSummaryEmail(recipient: string, summary: string) {
  const apiKey = process.env.RESEND_API_KEY;
  
  if (!apiKey) {
    console.warn("RESEND_API_KEY is not configured. Email sending skipped.");
    return { skipped: true, reason: "API Key missing" };
  }

  const resend = new Resend(apiKey);

  try {
    const { data, error } = await resend.emails.send({
      from: 'Rabbitt AI <onboarding@resend.dev>', // Resend default testing domain
      to: recipient,
      subject: "📊 Quarterly Sales Insight Brief",
      html: `<div style="font-family: sans-serif; line-height: 1.6; color: #333;">
              <h2 style="color: #2563eb;">Sales Insight Brief</h2>
              <div style="white-space: pre-wrap; background: #f4f4f4; padding: 15px; border-radius: 8px; font-family: monospace;">${summary}</div>
              <hr />
              <p style="font-size: 0.8em; color: #666;">Generated by Rabbitt AI Sales Insight Automator</p>
            </div>`,
    });

    if (error) {
      throw new Error(error.message);
    }

    console.log("Email sent successfully via Resend:", data?.id);
    return data;
  } catch (err: any) {
    console.error("Resend error:", err);
    throw new Error(`Failed to send email via Resend: ${err.message}`);
  }
}
